# This is a generated template. Modify the values as needed.

custom_function: module.test
dataset:
  data_generators:
    openai_prompt_data_generator:
      chunk_size: 1000
      input_function:
        description:
          Given an tech startup business, generate corresponding landing
          page headlines
        name: headline_generation_for_business
        parameters:
          tech_startup_business: str
      number_of_examples: 10
      openai_model_name: gpt-4
      output_path: demo/data/generated_examples.pkl
  source_type: machine_generated
description: Generated experiment config
# evaluators: []

# wrapper_configs: {}

# Variations allow for dynamic content during experiments.
# They are identified by a globally unique name. For example, in your code,
# you might reference a variation by its name, like:
# variation = StringWrapper("hello", 'test_experiment')
# In this config, you would define the variations associated with that name, e.g.

variations:
  - name: wrapper_name
    variations:
      - value_type: str
        value: "example_variation"
        instantiated_value: "example_variation"
