# This is a generated template. Modify the values as needed.

custom_function: /Users/taofeng/YiVal/demo.headline_generation.headline_generation
dataset:
  data_generators:
    openai_prompt_data_generator:
      chunk_size: 1000
      input_function:
        description:
          Given an tech startup business, generate one corresponding landing
          page headline
        name: headline_generation_for_business
        parameters:
          tech_startup_business: str
      number_of_examples: 10
      openai_model_name: gpt-4
      output_path: generated_examples.pkl
  source_type: machine_generated
description: Generated experiment config

evaluators:
  - evaluator_type: all
    input_description:
      Given an tech startup business, generate one corresponding landing
      page headline
    metric_calculators: []
    name: openai_elo_evaluator
    openai_model_name: gpt-4

selection_strategy:
  ahp_selection:
    criteria:
      - openai_elo_evaluator
      - average_token_usage
      - average_latency
    criteria_maximization:
      openai_elo_evaluator: true
      average_latency: false
      average_token_usage: false
    criteria_weights:
      openai_elo_evaluator: 0.6
      average_latency: 0.2
      average_token_usage: 0.2

# wrapper_configs: {}

# Variations allow for dynamic content during experiments.
# They are identified by a globally unique name. For example, in your code,
# you might reference a variation by its name, like:
# variation = StringWrapper("hello", 'test_experiment')
# In this config, you would define the variations associated with that name, e.g.

variations:
  - generator_config:
      input_description:
        Given an tech startup business, generate one corresponding landing
        page headline
      input_test_cases: ["AI law firm", "AI sales agent"]
      number_of_variations: 5
      openai_model_name: gpt-4
      output_path: generated_prompt.pkl
    generator_name: openai_prompt_based_variation_generator
    name: task
    variations:
      - instantiated_value: Generate landing page headline for
        value: Generate landing page headline for
        value_type: str
        variation_id: null
