# This is a generated template. Modify the values as needed.

custom_function: module.test
dataset:
  data_generators:
    openai_prompt_data_generator:
      chunk_size: 1000
      diversify: false
      input_function:
        description:
          Given an tech startup business, generate a corresponding landing
          page headline
        name: headline_generation_for_business
        parameters:
          tech_startup_business: str
      number_of_examples: 5
      openai_model_name: gpt-4
      output_path: null
      prompt:
        "\n            Please provide a concrete and realistic test case as\
        \ a dictionary for function invocation using the ** operator.\n          \
        \  Only include parameters, excluding description and name.\n            Ensure\
        \ it's succinct and well-structured.\n            **Only provide the dictionary.**\n\
        \            "
  source_type: machine_generated
description: Generated experiment config
evaluators:
  - name: openai_elo_evaluator
    openai_elo_evaluator:
      display_name: null
      evaluator_type: all
      input_description: This is a description.
      metric_calculators: []
      name: openai_elo_evaluator
      openai_model_name: gpt-4

  # wrapper_configs: {}
  - generator_config:
      diversify: false
      max_tokens: 7000
      number_of_variations: 5
      openai_model_name: gpt-4
      output_path: null
      prompt:
        - content: "

            Your mission is to craft system prompts tailored for GPT-4. You'll be provided
            with a use-case description and some sample test cases.

            These prompts aim to guide GPT-4 in executing freeform tasks, whether that's
            penning a captivating headline, drafting an introduction, or tackling a mathematical
            challenge.

            In your designed prompt, delineate the AI's role using lucid English. Highlight
            its perceptual field and the boundaries of its responses. Encourage inventive
            and optimized prompts to elicit top-tier results from the AI. Remember, GPT-4
            is self-aware of its AI nature; no need to reiterate that.

            The efficacy of your prompt determines your evaluation. Stay authentic! Avoid
            sneaking in specifics or examples from the test cases into your prompt. Such
            maneuvers will lead to immediate disqualification.

            Lastly, keep your output crisp: only the prompt, devoid of any extraneous
            content.

            "
          role: system
        - content:
            "Here are some test cases: AI, Weapon\n\n Here is the description of\
            \ the use-case: Given \\{area\\}, write a tech startup headline"
          role: user
      variables: null
    generator_name: openai_prompt_based_variation_generator
    name: task
    variations:
      - instantiated_value: manual test
        value: manual test
        value_type: str
        variation_id: null
