# This is a generated template. Modify the values as needed.

custom_function: module.test
dataset:
  data_generators:
    openai_prompt_data_generator:
      chunk_size: 1000
      input_function:
        description: Given an tech startup business, generate corresponding landing
          page headlines
        name: headline_generation_for_business
        parameters:
          tech_startup_business: str
      number_of_examples: 10
      openai_model_name: gpt-4
      output_path: null
  source_type: machine_generated
description: Generated experiment config
evaluators:
- evaluator_type: all
  input_description: This is a description.
  metric_calculators: []
  name: openai_elo_evaluator
  openai_model_name: gpt-4

# wrapper_configs: {}

variations:
- generator_config:
    input_description: This is a description.
    input_test_cases: []
    number_of_variations: 5
    openai_model_name: gpt-4
    output_path: null
  generator_name: openai_prompt_based_variation_generator
  name: task
  variations:
  - instantiated_value: manual test
    value: manual test
    value_type: str
    variation_id: null

    # Variations allow for dynamic content during experiments.
    # They are identified by a globally unique name. For example, in your code,
    # you might reference a variation by its name, like:
    # variation = StringWrapper("hello", 'test_experiment')
    # In this config, you would define the variations associated with that name.
    