# This is a generated template. Modify the values as needed.
description: Config for auto prompt demo

custom_function: yival.demo.headline_generation.headline_generation
dataset:
  data_generators:
    openai_prompt_data_generator:
      chunk_size: 1000
      diversify: false
      input_function:
        description:
          Given an tech startup business, generate a corresponding landing
          page headline
        name: headline_generation_for_tech_startup_business
        parameters:
          tech_startup_business: str
      number_of_examples: 3
      model_name: gpt-4
      output_path: demo_generated_examples.pkl
      prompt: |-
        Please provide a concrete and realistic test case as
        a dictionary for function invocation using the ** operator.
        Only include parameters, excluding description and name and ensure
        it's succinct and well-structured.

        **Only provide the dictionary.**

  source_type: machine_generated

variations:
  - name: task
    generator_name: openai_prompt_based_variation_generator
    generator_config:
      diversify: false
      max_tokens: 7000
      number_of_variations: 2
      model_name: gpt-4
      output_path: demo_generated_prompt.pkl
      prompt:
        - content: |-

            Your mission is to craft prompts tailored for GPT-4. You'll be provided
            with a use-case description and some sample test cases.

            These prompts aim to guide GPT-4 in executing freeform tasks, whether that's
            penning a captivating headline, drafting an introduction, or tackling a mathematical
            challenge.

            In your designed prompt, delineate the AI's role using lucid English. Highlight
            its perceptual field and the boundaries of its responses. Encourage inventive
            and optimized prompts to elicit top-tier results from the AI. Remember, GPT-4
            is self-aware of its AI nature; no need to reiterate that.

            The efficacy of your prompt determines your evaluation. Stay authentic! Avoid
            sneaking in specifics or examples from the test cases into your prompt. Such
            maneuvers will lead to immediate disqualification.

            Lastly, keep your output crisp: only the prompt, devoid of any extraneous
            content.

          role: system
        - content: |-
            Use cae description: Given an tech startup business, generate a corresponding landing page headline
            Test Cases: Food Delivery, AI Developer tools.
          role: user
        - content: |-
            {tech_startup_business} represent the specific test cases.
          role: user
      variables:
        - tech_startup_business
    variations:
      - instantiated_value: Generate landing page headline for {tech_startup_business}
        value: Generate landing page headline for {tech_startup_business}
        value_type: str
        variation_id: null

human_rating_configs:
  - name: clarity
    instructions: Rate whether the headline clearly state what the start is doing
    scale: [1, 5]

  - name: relevance
    instructions: Rate whether the headline is relevant
    scale: [1, 5]

evaluators:
  - evaluator_type: comparison
    alpaca_annotator_name: alpaca_eval_gpt4
    metric_calculators:
      - method: AVERAGE
    name: alpaca_eval_evaluator
