custom_function: /Users/taofeng/YiVal/demo.auto_prompt_bot.reply
dataset:
  source_type: user_input
description: Basic config for interactive mode
evaluators: []

custom_variation_generators:
  retrivel_variation_generator:
    class: /Users/taofeng/YiVal/demo/prompts_retrivel/retrivel_variation_generator.RetrivelVariationGenerator
    config_cls: /Users/taofeng/YiVal/demo/prompts_retrivel/retrivel_variation_generator_config.RetrivelVariationGeneratorConfig

variations:
  - name: prompt
    generator_config:
      use_case: "travel guide"
    generator_name: retrivel_variation_generator
