custom_function: demo.logo_generation.logo_generation
description: Generated experiment config
dataset:
  data_generators:
    openai_prompt_data_generator:
      chunk_size: 100000
      diversify: true
      prompt:
          "Please provide a concrete and realistic test case as a dictionary for function invocation using the ** operator.
          Only include parameters, excluding description and name.
          Ensure it's succinct and well-structured.
          **Only provide the dictionary.**"
      input_function:
        description:
          Given an tech startup business, generate a corresponding landing
          page headline
        name: headline_generation_for_business
        parameters:
          tech_startup_business: str
      number_of_examples: 1
      openai_model_name: gpt-4
      output_path: null
  source_type: machine_generated

variations:
  - name: task
    variations:
      - instantiated_value: Generate logo image for
        value: Generate landing page logo image for
        value_type: str
        variation_id: null
    generator_name: openai_prompt_based_variation_generator
    generator_config:
      openai_model_name: gpt-4
      number_of_variations: 1
      diversify: true
      variables: null
      prompt: 
        - content: |-
            Your objective is to construct a concise instruction prompt for GPT-4.
            Task: Given an tech startup business, generate one corresponding logo image which is really attracting to all people.
            The name of the company will be add to the end of the prompt.
            keep your output crisp: only the prompt, devoid of any extraneous content.

          role: system

evaluators: []
